
name: Build
on:
  push:
    branches:
      - 'trunk'
      - 'prerelease'
      # The `**/*/` works around the fact that GitHub considers a leading `**/` as meaning "zero or more path components" where we want "one or more".
      - '**/*/branch-**'
  pull_request:
concurrency:
  # Cancel concurrent jobs on pull_request but not push, by including the run_id in the concurrency group for the latter.
  group: build-${{ github.event_name == 'push' && github.run_id || 'pr' }}-${{ github.ref }}
  cancel-in-progress: true

env:
  COMPOSER_ROOT_VERSION: "dev-trunk"
  # Work around a bug in node 18.18.0. See https://github.com/webpack-contrib/thread-loader/issues/191 for details.
  UV_USE_IO_URING: 0

jobs:
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-0a328b562c2920589
          ec2-instance-type: c5a.xlarge
          subnet-id: subnet-1c62be67
          security-group-id: sg-08bb38eecd42932f9
#          iam-role-name: my-role-name # optional, requires additional permissions
#          aws-resource-tags: > # optional, requires additional permissions
#            [
#              {"Key": "Name", "Value": "ec2-github-runner"},
#              {"Key": "GitHubRepository", "Value": "${{ github.repository }}"}
#            ]
  build:
    name: Build all projects
    runs-on: ${{ needs.start-runner.outputs.label }} # run the job on the newly created runner
    needs: start-runner
    timeout-minutes: 30  # 2023-05-25: Build times have crept up to ~15–25+ minutes as we've added more projects, bump to 30.
    env:
      # Hard-code a specific directory to avoid paths in vendor/composer/installed.json changing every build.
      BUILD_BASE: /tmp/jetpack-build
      # This string is used as a unique identifier of test reminder comments on PRs.
      TEST_COMMENT_INDICATOR: "<!-- wpcom-reminder-comment -->"
      COMPOSER_ALLOW_SUPERUSER: 1
    outputs:
      any_plugins: ${{ steps.plugins.outputs.any }}
      changed_projects: ${{ steps.changed.outputs.projects }}

    steps:
      - uses: actions/checkout@v3

      # For pull requests, list-changed-projects.sh needs the merge base.
      # But it doesn't have to be checked out.
      - name: Deepen to merge base
        if: github.event_name == 'pull_request'
        uses: ./.github/actions/deepen-to-merge-base
        with:
          checkout: false

      - name: Setup tools
        uses: ./.github/actions/tool-setup

      - name: Pnpm install
        run: pnpm install

      - name: Detect changed projects
        id: changed
        run: |
          CHANGED="$(EXTRA=build .github/files/list-changed-projects.sh)"
          echo "projects=${CHANGED}" >> "$GITHUB_OUTPUT"

      - name: Check if a WordPress.com test reminder comment is needed.
        id: check-test-reminder-comment
        uses: actions/github-script@v6
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name }}
        env:
          CHANGED: ${{ steps.changed.outputs.projects }}
        with:
          script: |
            const checkTestReminderComment = require('.github/files/build-reminder-comment/check-test-reminder-comment.js')
            const data = await checkTestReminderComment( github, context, core );
            return data;

      # We need the tree (but not the blob) for packages that will have -alpha version numbers so the timestamp appending works right.
      - name: Deepen tree for packages
        env:
          CHANGED: ${{ steps.changed.outputs.projects }}
        run: |
          mapfile -t PROJECTS < <(jq -r 'to_entries[] | select( .value ) | .key' <<<"$CHANGED")
          if [[ ${#PROJECTS[@]} -gt 0 ]]; then
            depth=$( git rev-list --count --first-parent HEAD )
            [[ "$depth" -lt 1000 ]] && depth=1000
            BASE=$PWD
            REF=$(git rev-parse HEAD)
            for SLUG in $(pnpm jetpack dependencies list --add-dependencies --extra="build" --ignore-root "${PROJECTS[@]}"); do
              [[ "$SLUG" == packages/* ]] || continue
              cd "$BASE/projects/$SLUG/"
              CHANGES_DIR="$(jq -r '.extra.changelogger["changes-dir"] // "changelog"' composer.json)"
              [[ -d "$CHANGES_DIR" && -n "$(ls -- "$CHANGES_DIR")" ]] || continue
              echo "Checking depth for $SLUG"
              while git log --format='%h, %D,' -1 . | grep ', grafted,'; do
                depth=$((depth * 2))
                echo "::group::Deepen to $depth"
                echo "/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=$depth --filter=blob:none origin $REF"
                /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=$depth --filter=blob:none origin "$REF"
                echo "::endgroup::"
              done
            done
          fi

      - name: Build changed projects
        id: build
        env:
          CHANGED: ${{ steps.changed.outputs.projects }}
        run: |
          mapfile -t PROJECTS < <(jq -r 'to_entries[] | select( .value ) | .key' <<<"$CHANGED")
          if [[ ${#PROJECTS[@]} -eq 0 ]]; then
            echo "Nothing to build. Generating empty artifact."
            mkdir "$BUILD_BASE"
            touch "$BUILD_BASE/mirrors.txt"
          else
            pnpm jetpack build -v --no-pnpm-install --for-mirrors="$BUILD_BASE" "${PROJECTS[@]}"
          fi

      - name: Filter mirror list for release branch
        if: github.ref == 'refs/heads/prerelease' || contains( github.ref, '/branch-' )
        run: .github/files/filter-mirrors-for-release-branch.sh

      - name: Determine plugins to publish
        id: plugins
        run: |
          jq -r 'if .extra["mirror-repo"] and ( .extra["beta-plugin-slug"] // .extra["wp-plugin-slug"] ) then [ ( input_filename | sub( "/composer\\.json$"; "" ) ), .extra["mirror-repo"], .extra["beta-plugin-slug"] // .extra["wp-plugin-slug"] ] else empty end | @tsv' projects/plugins/*/composer.json | while IFS=$'\t' read -r SRC MIRROR SLUG; do
            if [[ -e "$BUILD_BASE/$MIRROR" ]] && grep -q --fixed-strings --line-regexp "$MIRROR" "$BUILD_BASE/mirrors.txt"; then
              printf '%s\t%s\t%s\n' "$SRC" "$MIRROR" "$SLUG"
            fi
          done > "$BUILD_BASE/plugins.tsv"
          if [[ -s "$BUILD_BASE/plugins.tsv" ]]; then
            cat "$BUILD_BASE/plugins.tsv"
            echo "any=true" >> "$GITHUB_OUTPUT"
          else
            echo "No plugins were built"
            echo "any=false" >> "$GITHUB_OUTPUT"
          fi

      # GitHub's artifact stuff doesn't preserve permissions or file case. Sigh.
      # This is the official workaround: https://github.com/actions/upload-artifact#maintaining-file-permissions-and-case-sensitive-files
      # It'll also make it faster to upload and download though, so maybe it's a win anyway.
      - name: Create archive
        run: tar --owner=0 --group=0 --xz -cvvf build.tar.xz -C "$BUILD_BASE" --transform 's,^\.,build,' .

      - name: Store build as artifact
        uses: actions/upload-artifact@v3
        with:
          name: jetpack-build
          path: build.tar.xz
          # Only need to retain for a day since the beta builder slurps it up to distribute.
          retention-days: 1

      - name: Store plugins.tsv as artifact
        if: steps.plugins.outputs.any == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: plugins.tsv
          path: ${{ env.BUILD_BASE }}/plugins.tsv
          # We don't really care about this artifact, its presence is a flag to the post-build job.
          retention-days: 1

      - name: Update reminder with testing instructions
        id: update-reminder-comment
        uses: actions/github-script@v6
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name && fromJSON(steps.check-test-reminder-comment.outputs.result)['commentId'] != 0 }}
        env:
          BRANCH_NAME: ${{ github.head_ref }}
          DATA: ${{ steps.check-test-reminder-comment.outputs.result }}
        with:
          script: |
            const { BRANCH_NAME, TEST_COMMENT_INDICATOR } = process.env;
            const data = JSON.parse( process.env.DATA );
            const commands = data.projects.reduce( ( acc, cur ) => {
              return acc += `
              \`\`\`
              bin/jetpack-downloader test ${ cur } ${ BRANCH_NAME }
              \`\`\`
              `;
            }, '' );

            let jetpackMuWPcomLine = '';
            if ( data.projects.includes( 'jetpack-mu-wpcom-plugin' ) ) {
              jetpackMuWPcomLine = "  - For \`jetpack-mu-wpcom\` changes, also add \`define( 'JETPACK_MU_WPCOM_LOAD_VIA_BETA_PLUGIN', true );\` to your \`wp-config.php\` file.";
            }

            const commentBody = `${ TEST_COMMENT_INDICATOR }
            Are you an Automattician? Please test your changes on all WordPress.com environments to help mitigate accidental explosions.

            - To test on WoA, go to the Plugins menu on a WordPress.com Simple site. Click on the "Upload" button and follow the upgrade flow to be able to upload, install, and activate [the Jetpack Beta plugin](https://jetpack.com/download-jetpack-beta/). Once the plugin is active, go to Jetpack > Jetpack Beta, select your plugin, and enable the \`${ BRANCH_NAME }\` branch.
            ${ jetpackMuWPcomLine }
            - To test on Simple, run the following command on your sandbox:
            ${ commands }

            *Interested in more tips and information?*

            - In your local development environment, use the \`jetpack rsync\` command to sync your changes to a WoA dev blog.
            - Read more about our development workflow here: PCYsg-eg0-p2
            - Figure out **when your changes will be shipped to customers** here: PCYsg-eg5-p2`;
            await github.rest.issues.updateComment( {
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody,
              comment_id: +data.commentId,
            } );

  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner # required to get output from the start-runner job
      - build # required to wait when the main job is done
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
